# Generated by Django 3.2 on 2022-05-23 22:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_rack_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4e8d136d-a766-493a-9679-a96d80c3a4e7')),
        ),
    ]
