# Generated by Django 3.2 on 2022-05-24 15:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_rack_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b4b07c35-1bd2-4168-aa42-eaaeb59771f4')),
        ),
    ]
