# Generated by Django 3.2 on 2022-05-27 16:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20220527_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('c', 'Science'), ('h', 'History'), ('h', 'Horror'), ('f', 'Fiction'), ('r', 'Romace'), ('l', 'Literature'), ('r', 'Technology')], max_length=1),
        ),
        migrations.AlterField(
            model_name='bookitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ab52e05c-f638-4e7b-bc58-0f52d57688c1')),
        ),
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6704a28c-500c-4dc0-965f-1f8f02d26bba')),
        ),
    ]
