# Generated by Django 3.2 on 2022-05-27 16:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20220527_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookitem',
            old_name='rent',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('c', 'Science'), ('h', 'History'), ('h', 'Horror'), ('f', 'Fiction'), ('r', 'Romace'), ('l', 'Literature'), ('r', 'Romace'), ('l', 'Literature'), ('t', 'Technology')], max_length=1),
        ),
        migrations.AlterField(
            model_name='bookitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('741ef1ed-20d3-49e8-91d5-630278bbd412')),
        ),
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7b5afc9a-58e7-4501-85d9-5089436b854f')),
        ),
    ]
